# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trans', '0002_auto_20170110_1922'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecategory',
            name='title_language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.CASCADE, to='field_trans.Language'),
            preserve_default=False,
        ),
    ]
