# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170104_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
    ]
