# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pagecategory_title_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecategory',
            old_name='title_language',
            new_name='language',
        ),
    ]
