# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170104_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
