# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170110_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecategory',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
            preserve_default=False,
        ),
    ]
