# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfeed2', '0002_auto_20170220_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='general', max_length=120),
        ),
    ]
