# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfeed2', '0003_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('general', 'general'), ('classified', 'classified'), ('event', 'event')], default='general', max_length=120),
        ),
    ]
