# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_code_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
