# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161130_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perma_code',
            field=models.CharField(default=123456789012345678901234567890123456789012345678901234567890L, max_length=60),
            preserve_default=False,
        ),
    ]
