# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170110_0342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageOption',
            new_name='Language',
        ),
    ]
