# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file_base_name', models.CharField(blank=True, max_length=60, null=True)),
                ('app_name', models.CharField(blank=True, max_length=30, null=True)),
                ('model_name', models.CharField(blank=True, max_length=30, null=True)),
                ('uploader', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
