# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('table_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_id', models.IntegerField()),
                ('language', models.CharField(max_length=32)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set([('table_name', 'field_name', 'field_id', 'language')]),
        ),
    ]
