# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='field_trans.Language'),
        ),
    ]
