# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_images', models.BooleanField(default=True)),
                ('allow_reactions', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microfeed.PostThread'),
        ),
    ]
