# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfeed', '0003_auto_20161208_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='test', max_length=3000, verbose_name='body'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postimage',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
